global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ticketcore_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'backend:8000' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: 'worker'
    static_configs:
      - targets: [ 'worker:8001' ]