apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-deployment
  labels:
    app: ticketcore-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketcore-pgbouncer
  template:
    metadata:
      labels:
        app: ticketcore-pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pgbouncer-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ticketcore-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketcore-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ticketcore-secret
                  key: POSTGRES_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-svc
spec:
  selector:
    app: ticketcore-pgbouncer
  ports:
    - port: 5432