apiVersion: batch/v1
kind: Job
metadata:
  name: ticketcore-migration-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: run-migrations
          image: 047646727711.dkr.ecr.eu-central-1.amazonaws.com/ticketcore-backend:latest
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "alembic upgrade head" ]
          envFrom:
            - configMapRef:
                name: ticketcore-config
            - secretRef:
                name: ticketcore-secret
          env:
            - name: POSTGRES_HOST
              value: "postgres-svc"