"""add_ticket_owner

Revision ID: 6024bf1355a1
Revises: 5cd117e3f448
Create Date: 2026-02-04 13:54:48.448197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6024bf1355a1'
down_revision: Union[str, Sequence[str], None] = '5cd117e3f448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_tickets_owner_id_users'), 'tickets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tickets_owner_id_users'), 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'owner_id')
    # ### end Alembic commands ###
