"""migrate architecture to ticket types

Revision ID: a1c2a40c6c7c
Revises: 395c86797555
Create Date: 2026-03-01 22:43:43.687615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c2a40c6c7c'
down_revision: Union[str, Sequence[str], None] = '395c86797555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tickets_quantity', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_ticket_types_check_ticket_price')),
    sa.CheckConstraint('tickets_quantity > 0', name=op.f('ck_ticket_types_check_ticket_quantity')),
    sa.CheckConstraint('tickets_quantity >= tickets_sold', name=op.f('ck_ticket_types_check_sold_limit')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_types_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_types'))
    )
    op.drop_column('events', 'tickets_sold')
    op.drop_column('events', 'tickets_quantity')
    op.add_column('tickets', sa.Column('ticket_type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_tickets_event_id_events'), 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_ticket_type_id_ticket_types'), 'tickets', 'ticket_types', ['ticket_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tickets', 'price')
    op.drop_column('tickets', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_tickets_ticket_type_id_ticket_types'), 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_event_id_events'), 'tickets', 'events', ['event_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tickets', 'ticket_type_id')
    op.add_column('events', sa.Column('tickets_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('tickets_sold', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('ticket_types')
    # ### end Alembic commands ###
