{
 "title": "Main dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "db_pool_size", "legendFormat": "Max Size" },
    { "expr": "db_pool_checkedin", "legendFormat": "Idle" },
    { "expr": "db_pool_checkedout", "legendFormat": "Active" },
    { "expr": "db_pool_overflow", "legendFormat": "Overflow" }
   ]
  },
  {
   "title": "API: Load (RPS by status)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Business Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(business_tickets_sold_total[5m]))",
     "legendFormat": "sold"
    },
    {
     "expr": "sum(increase(business_tickets_reserved_total[5m]))",
     "legendFormat": "reserved"
    },
    {
     "expr": "sum(increase(business_tickets_canceled_total[5m]))",
     "legendFormat": "canceled"
    }
   ]
  },
  {
   "title": "Worker: p95 Task completion time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_task_duration_seconds_bucket[5m])) by (le, task_name))",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}